config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_comment_counter
  after_destroy :decrement_comment_counter

  def increment_comment_counter
    post = Post.find(post_id)
    post.increment!(:comments_counter)
  end

  def decrement_comment_counter
    post = Post.find(post_id)
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :increment_like_counter

  def increment_like_counter
    post = Post.find(post_id)
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :author, class_name: 'User'

  after_save :increment_post_counter
  after_destroy :decrement_post_counter

  validates :title, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  def increment_post_counter
    user = User.find(author_id)
    user.increment!(:posts_counter)
  end

  def decrement_post_counter
    user = User.find(author_id)
    user.decrement!(:posts_counter)
  end

  def recent_comments
    comments.order('created_at Desc').limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  validates :name, length: { minimum: 1 }
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order('created_at Desc').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to root_path, notice: 'Successfully created comment.'
    else
      render :new
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])

    if @comment.destroy
      redirect_to root_path, notice: 'Successfuly deleted comment.'
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(author_id: current_user.id, post_id: params[:post_id])

    redirect_to root_path, notice: 'Successfully liked.' if @like.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to root_path, notice: 'Successfully created post.'
    else
      render :new
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])

    if @post.destroy
      redirect_to root_path, notice: 'Successfuly deleted post.'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="container">
  <%= form_with model: @comment, url: user_post_comments_path, data: {turbo: false } do |form| %>
    <% if @comment.errors.any? %>
      <div class="alert alert-danger mt-4" role="alert">
        <% @comment.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :text, "Comment:", class: "form-label" %>
      <%= form.text_area :text, class: "form-control", placeholder: "The best place in Middle-earth" %>
    </div>
    <%= form.submit "Create Comment", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container">
      <%= render partial: "shared/flash" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="center flex-column m-3">
  <%= render partial: "shared/user", locals: {user: @user}%>
  <div class="d-flex flex-column w-50 w-100-mobile">
    <% if @user.posts.empty? %>
      <p class="lead text-center">No posts yet!</p>
    <% else %>
      <% @user.posts.includes(:comments).each do |post| %>
        <div class="d-flex flex-column bg-light p-2 border mb-3">
          <div class="d-flex align-items-center">
            <h5 class="me-auto"><%= link_to post.title, user_post_path(id: post.id), class: "no-style" %></h5>
          </div>
          <p><%= post.text %></p>
          <p class="small align-self-end">
            Comments
            <span class="badge bg-secondary">
              <%= post.comments_counter %>
            </span>
            Likes
            <span class="badge bg-secondary">
              <%= post.likes_counter %>
            </span>
          </p>
          <div class="d-flex flex-column">
            <h6>Recent comments</h6>
            <ul class="group-item">
              <% if post.comments.empty? %>
                <li class="list-group-item">No comments yet.</li>
              <% else %>
                <% post.recent_comments.includes(:author).each do |comment| %>
                  <li class="list-group-item">
                    <span class="lead">
                      <%= comment.author.name %>:
                    </span>
                  <%= comment.text %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
    <%= button_to "Pagination", "", class: "btn btn-primary" %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= form_with model: @post, url: user_posts_path, data: {turbo: false } do |form| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger mt-4" role="alert">
      <% @post.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
    <div class="mb-3">
      <%= form.label :title, "Title:", class: "form-label" %>
      <%= form.text_field :title, class: "form-control", placeholder: "Misty Mountains Cold" %>
    </div>
    <div class="mb-3">
      <%= form.label :text, class: "form-label" %>
      <%= form.text_area :text, class: "form-control", placeholder: "The best place in Middle-earth" %>
    </div>
    <%= form.submit "Create Post", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="center-body mt-3">
  <div class="d-flex flex-column bg-light p-2 border mb-3">
    <div class="d-flex align-items-baseline">
      <h5 class="me-auto"><%= @post.title %> by <%= @post.author.name %></h5>
        <p class="small">
          Comments
          <span class="badge bg-secondary">
            <%= @post.comments_counter %>
          </span>
          Likes
          <span class="badge bg-secondary">
            <%= @post.likes_counter %>
          </span>
        </p>
    </div>
    <p><%= @post.text %></p>
    <div class="d-flex flex-column">
      <h6>Comments</h6>
      <ul class="group-item">
        <% if @post.comments.empty? %>
          <li class="list-group-item">No comments yet.</li>
        <% else %>
          <% @post.comments.includes(:author).each do |comment| %>
            <li class="list-group-item position-relative ">
              <span class="lead">
                <%= comment.author.name %>:
              </span>
              <%= comment.text %>
              <% if can? :destroy, comment %>
                <%= button_to user_post_comment_path(@post.author, @post, comment), method: :delete, class: "trash-btn" do%>
                <svg class='trash-icon text-danger' viewBox="0 0 24 24">
                  <path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
                </svg>
                <%end%>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <div class="d-flex gap-2">
        <%= link_to "Add a comment", new_user_post_comment_path(post_id: @post.id), class: "btn btn-primary align-self-start" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
          <%= form.submit "Like", class: "btn btn-primary" %>
        <% end %>
        <% if can? :manage, @post %>
        <%= button_to "Delete Post", user_post_path(@post), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Blog App", users_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Home", users_path, class: "nav-link active" %>
        </div>
      </div>
  </div>
</nav>

app/views/shared/_user.html.erb
<div class="d-flex w-50 w-100-mobile mb-3">
  <img src=<%= user.photo %> alt="User avatar", class="img-fluid img-thumbnail me-3">
  <div class="d-flex flex-column align-items-end justify-content-center w-100 bg-light p-2">
    <h2 class="align-self-start"><%= user.name %></h2>
    <p>Number of posts
      <span class="badge bg-secondary">
        <%= user.posts_counter %>
      <span>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<div class="center flex-column mt-3 mx-3">
  <h1>Welcome to Blog App</h1>
  <% @users.each do |user| %>
    <div class="d-flex w-50 w-100-mobile mb-3">
       <img src=<%= user.photo %> alt="User avatar", class="img-fluid img-thumbnail me-3">
      <div class="d-flex flex-column align-items-end justify-content-center w-100 bg-light p-2">
        <%= link_to "Open Profile", user_path(user.id), class: "btn btn-primary" %>
        <h2 class="align-self-start"><%= user.name %></h2>
        <p>
          Number of posts
          <span class="badge bg-secondary">
            <%= user.posts_counter %>
          <span>
        </p>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="center flex-column m-3">
  <%= render partial: "shared/user", locals: {user: @user}%>
  <div class="w-50 w-100-mobile mb-3 bg-light p-2 border">
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>
  <div class="d-flex flex-column w-50 w-100-mobile">
    <% @user.recent_posts.each do |post| %>
      <div class="d-flex flex-column bg-light p-2 border mb-3">
        <h5><%= link_to post.title, user_post_path(@user, post.id), class: "no-style" %></h5>
        <p><%= post.text %></p>
        <p class="small align-self-end">
          Comments
          <span class="badge bg-secondary">
            <%= post.comments_counter %>
          </span>
          Likes
          <span class="badge bg-secondary">
            <%= post.likes_counter %>
          </span>
        </p>
      </div>
    <% end %>
  </div>
  <%= link_to "See all posts" , user_posts_path(@user.id), class: "btn btn-primary" %>
</div>